// Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/* automatically generated by rust-bindgen 0.69.4 */
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
pub type ssr_ss_id = ::std::os::raw::c_uint;
pub const SS_ID_LPASS: ssr_ss_id = 1;
pub const SS_ID_MODEM: ssr_ss_id = 2;
pub const SS_ID_SLPI: ssr_ss_id = 8;
pub const SS_ID_CDSP: ssr_ss_id = 16;
pub const SS_ID_CDSP1: ssr_ss_id = 32;
pub const SS_ID_GPDSP0: ssr_ss_id = 64;
pub const SS_ID_GPDSP1: ssr_ss_id = 128;
pub const SS_ID_INVALID: ssr_ss_id = 255;

pub type ssr_events = ::std::os::raw::c_uint;
pub const SSR_EVENT_FAULT_NOTIFY: ssr_events = 1;
pub const SSR_EVENT_RESTART_START: ssr_events = 2;
pub const SSR_EVENT_RESTART_COMPLETE: ssr_events = 4;
pub const SSR_EVENT_RESTART_FAILED: ssr_events = 8;
pub const SSR_EVENT_PRE_DS: ssr_events = 16;
pub const SSR_SOC_RESTART: ssr_events = 32;
pub const SSR_EVENT_DUMMY: ssr_events = 128;

pub const MAGIC_LPASS: u64 = 0x6C70617373;
pub const MAGIC_SLPI: u64 = 0x5A1252177B;
pub const MAGIC_CDSP0: u64 = 0x8C95619236;
pub const MAGIC_CDSP1: u64 = 0x4AC385218B;
pub const MAGIC_GPDSP0: u64 = 0x9C59169846;
pub const MAGIC_GPDSP1: u64 = 0x7A47787699;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ssr_rm_msg_t {
    pub msg_type: ::std::os::raw::c_int,
    pub ss_id: ssr_ss_id,
    pub ss_event: ssr_events,
}
#[test]
fn bindgen_test_layout_ssr_rm_msg_t() {
    const UNINIT: ::std::mem::MaybeUninit<ssr_rm_msg_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<ssr_rm_msg_t>(),
        12usize,
        concat!("Size of: ", stringify!(ssr_rm_msg_t))
    );
    assert_eq!(
        ::std::mem::align_of::<ssr_rm_msg_t>(),
        4usize,
        concat!("Alignment of ", stringify!(ssr_rm_msg_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).msg_type) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ssr_rm_msg_t),
            "::",
            stringify!(msg_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ss_id) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(ssr_rm_msg_t),
            "::",
            stringify!(ss_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ss_event) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(ssr_rm_msg_t),
            "::",
            stringify!(ss_event)
        )
    );
}
pub type ssr_rm_msg = ssr_rm_msg_t;
